#!/usr/bin/env bash
set -o errexit

ENVIRONMENT=${1:-"development"}
deploy_dir="/srv/web/apps/vivo_widgets_reporter"

case "$ENVIRONMENT" in
  development)
    SERVERS=("scholars-web-dev-01.oit.duke.local")
    ;;
  acceptance)
    SERVERS=("scholars-web-test-01.oit.duke.local" "scholars-web-test-02.oit.duke.local")
    ;;
  production)
    SERVERS=("scholars-web-01.oit.duke.local" "scholars-web-02.oit.duke.local")
    ;;
  *)
    echo "Usage: $0 {development|acceptance|production}"
    exit 1
esac

lein cljsbuild once production

for SERVER in "${SERVERS[@]}"; do
  echo "deploying to $ENVIRONMENT server: $SERVER..."

  echo "rsyncing files to $SERVER..."
  rsync -avz production.html torquebox@$SERVER:$deploy_dir/scholar_report.html

  echo "creating asset directory on $SERVER..."
  ssh torquebox@$SERVER "[ -d $deploy_dir/assets ] || mkdir $deploy_dir/assets"

  echo "rsyncing asset files to $SERVER..."
  rsync -avz assets/css/*.css torquebox@$SERVER:$deploy_dir/assets/css/
  rsync -avz assets/js/*.js torquebox@$SERVER:$deploy_dir/assets/js/
done
