#!/usr/bin/env bash

ENVIRONMENT=${1:-"development"}
SERVER="scholars-web-dev-01.oit.duke.local"
deploy_dir="/srv/web/apps/vivo_widgets_reporter"
echo "deploying to $ENVIRONMENT server: $SERVER..."

lein cljsbuild once production

echo "creating asset directory..."
ssh torquebox@$SERVER "mkdir $deploy_dir/assets"

echo "rsyncing files..."
rsync -avz production.html torquebox@$SERVER:$deploy_dir/scholar_report.html
rsync -avz vivo_widgets_reporter.production.js torquebox@$SERVER:/srv/web/apps/vivo_widgets_reporter/
rsync -avz assets/css/*.css torquebox@$SERVER:$deploy_dir/assets/css/
rsync -avz assets/js/*.js torquebox@$SERVER:$deploy_dir/assets/js/
